    emit:
    - "@typespec/openapi3"
    - "@typespec/http-server-csharp"
    options:
      "@typespec/openapi3":
        emitter-output-dir: "{project-root}/../server_inmem/wwwroot"
      "@typespec/http-server-csharp":
        emitter-output-dir: "{project-root}/../server_inmem"
        use-swaggerui: true
        overwrite: true
        emit-mocks: "mocks-and-project-files"